import { Expose, Type } from "class-transformer";
import type { ExpenseType } from "../../../generated/prisma/enums";
import { AssociateMinEntity } from "../../hr/attendance/entities/attendance.entity";

export class ExpenseEntity {
  @Expose()
  id!: string;

  @Expose()
  firmId!: string;

  @Expose()
  type!: ExpenseType;

  @Expose()
  category!: string;

  @Expose()
  description!: string;

  /** Prisma stores Decimal; expose as a JSON number. */
  @Expose()
  @Type(() => Number)
  amount!: number;

  @Expose()
  date!: Date;

  @Expose()
  vendor?: string | null;

  @Expose()
  paymentMethod?: string | null;

  @Expose()
  receiptUrl?: string | null;

  @Expose()
  associateId?: string | null;

  @Expose()
  loggedById?: string | null;

  @Expose()
  isAutoGenerated!: boolean;

  @Expose()
  createdAt!: Date;

  @Expose()
  @Type(() => AssociateMinEntity)
  associate?: AssociateMinEntity | null;
}
