[project]
name = "verdict"
version = "0.1.0"
description = "AI backend for Verdict"
readme = "README.md"
authors = [
    { name = "zas512", email = "[zainalis.914@gmail.com]" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
ai = "ai:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
