import re
from typing import Any

from src.config import settings
from src.logger import logger


class PIIFilter:
    """Detects and masks personally identifiable information (PII)."""

    PII_PATTERNS: list[tuple[str, str]] = [
        (r"\b\d{3}-\d{2}-\d{4}\b", "[REDACTED-SSN]"),
        (
            r"\b(?:\d{4}[-\s]?){3}\d{4}\b",
            "[REDACTED-CREDIT-CARD]",
        ),
        (
            r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,7}\b",
            "[REDACTED-EMAIL]",
        ),
        (
            r"\b(?:\+?1[-.\s]?)?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}\b",
            "[REDACTED-PHONE]",
        ),
    ]

    @classmethod
    def mask(cls, text: str) -> str:
        masked = text
        for pattern, replacement in cls.PII_PATTERNS:
            masked = re.sub(pattern, replacement, masked)
        return masked


class GuardrailManager:
    """
    Coordinates pre-retrieval, post-retrieval, and post-generation safety checks.
    """

    DEFAULT_DISCLAIMER: str = (
        "\n\n*Disclaimer: This response is generated by an AI assistant for informational and "
        "case research purposes only and does not constitute formal legal advice.*"
    )

    def __init__(self) -> None:
        self.enabled = settings.enable_guardrails
        self.min_chunk_score = settings.min_chunk_score

    def check_retrieval_confidence(
        self, chunks: list[dict[str, Any]]
    ) -> tuple[bool, list[dict[str, Any]]]:
        """
        Filters out chunks below minimum similarity threshold.
        Returns (has_sufficient_context, filtered_chunks).
        """
        if not self.enabled:
            return bool(chunks), chunks

        if not chunks:
            return False, []

        valid_chunks = [
            c for c in chunks if c.get("similarity_score", 0.0) >= self.min_chunk_score
        ]

        if not valid_chunks:
            logger.warning(
                f"Guardrail triggered: Top chunk score {chunks[0].get('similarity_score', 0.0)} "
                f"below minimum threshold ({self.min_chunk_score})"
            )
            return False, []

        return True, valid_chunks

    def sanitize_output(
        self,
        answer: str,
        include_disclaimer: bool = True,
        mask_pii: bool = False,
    ) -> str:
        """Sanitizes generated answer with optional PII masking and disclaimer."""
        result = answer
        if mask_pii:
            result = PIIFilter.mask(result)

        if include_disclaimer and self.DEFAULT_DISCLAIMER.strip() not in result:
            result = f"{result.strip()}{self.DEFAULT_DISCLAIMER}"

        return result


guardrails = GuardrailManager()
