"use client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { CustomTable } from "@/components/table";
import { formatPKR } from "@/lib/format";
import { getErrorMessage } from "@/lib/utils";
import type { ColumnConfig } from "@/types/tableTypes";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import {
  CalendarDays,
  HandCoins,
  Plus,
  Receipt,
  RefreshCcw,
  Repeat,
  Trash2,
  Wallet
} from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { SummaryStrip } from "../ui/summary-strip";
import { CreateExpenseDialog } from "./CreateExpenseDialog";
import { RecurringTemplatesDialog } from "./RecurringTemplatesDialog";
import { RecurringTemplatesSection } from "./RecurringTemplatesSection";

export interface ExpenseRecord {
  id: string;
  firmId: string;
  type: "FIXED" | "MANUAL";
  category: string;
  description: string;
  amount: number;
  date: string;
  vendor?: string | null;
  paymentMethod?: string | null;
  receiptUrl?: string | null;
  associateId?: string | null;
  loggedById?: string | null;
  isAutoGenerated: boolean;
  createdAt: string;
  associate?: {
    id: string;
    fullName: string;
    email: string | null;
  } | null;
}

export interface RecurringTemplate {
  id: string;
  category: string;
  description: string;
  amount: number;
  billingCycle: "MONTHLY" | "QUARTERLY" | "ANNUALLY";
  isActive: boolean;
  nextRunDate: string;
  createdAt: string;
}

function formatDate(dateIso: string): string {
  if (!dateIso) return "-";
  const d = new Date(dateIso);
  if (Number.isNaN(d.getTime())) return dateIso;
  return d.toLocaleDateString("en-PK", {
    day: "2-digit",
    month: "short",
    year: "numeric"
  });
}

interface ExpensesClientProps {
  userRole: string;
}

export function ExpensesClient({ userRole }: Readonly<ExpensesClientProps>) {
  const queryClient = useQueryClient();
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [isTemplateOpen, setIsTemplateOpen] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  const isOwner = userRole === "OWNER";

  const expensesQuery = useQuery<ExpenseRecord[]>({
    queryKey: ["expenses"],
    queryFn: async () => {
      const res = await fetch("/api/expenses");
      if (!res.ok) {
        const errorData = await res.json().catch(() => ({}));
        throw new Error(errorData.message || "Failed to fetch expenses");
      }
      return res.json();
    }
  });

  const templatesQuery = useQuery<RecurringTemplate[]>({
    queryKey: ["recurring-expenses"],
    queryFn: async () => {
      const res = await fetch("/api/recurring-expenses");
      if (!res.ok) {
        const errorData = await res.json().catch(() => ({}));
        throw new Error(
          errorData.message || "Failed to fetch recurring templates"
        );
      }
      return res.json();
    },
    enabled: isOwner
  });

  useEffect(() => {
    if (expensesQuery.error) {
      toast.error(
        getErrorMessage(expensesQuery.error, "Error loading expenses")
      );
    }
    if (templatesQuery.error) {
      toast.error(
        getErrorMessage(
          templatesQuery.error,
          "Error loading recurring templates"
        )
      );
    }
  }, [expensesQuery.error, templatesQuery.error]);

  const expenses = useMemo(
    () => expensesQuery.data ?? [],
    [expensesQuery.data]
  );
  const templates = useMemo(
    () => templatesQuery.data ?? [],
    [templatesQuery.data]
  );

  const stats = useMemo(() => {
    const now = new Date();
    const thisMonthKey = `${now.getFullYear()}-${String(
      now.getMonth() + 1
    ).padStart(2, "0")}`;
    let thisMonth = 0;
    let fixed = 0;
    let manual = 0;
    for (const e of expenses) {
      const amount = Number(e.amount) || 0;
      if (e.date?.startsWith(thisMonthKey)) thisMonth += amount;
      if (e.type === "FIXED") fixed += amount;
      else manual += amount;
    }
    const activeTemplates = templates.filter((t) => t.isActive).length;
    return { thisMonth, fixed, manual, activeTemplates };
  }, [expenses, templates]);

  const deleteExpense = async (expense: ExpenseRecord) => {
    if (
      !confirm(
        `Delete this ${expense.type === "FIXED" ? "fixed" : "manual"} expense? This cannot be undone.`
      )
    ) {
      return;
    }
    try {
      const base =
        expense.type === "FIXED" ? "fixed-expenses" : "manual-expenses";
      const res = await fetch(`/api/${base}/${expense.id}`, {
        method: "DELETE"
      });
      if (!res.ok) {
        const errorData = await res.json().catch(() => ({}));
        throw new Error(errorData.message || "Failed to delete expense");
      }
      toast.success("Expense deleted");
      await queryClient.invalidateQueries({ queryKey: ["expenses"] });
    } catch (err) {
      toast.error(getErrorMessage(err, "Error deleting expense"));
    }
  };

  const toggleTemplate = async (template: RecurringTemplate) => {
    try {
      const res = await fetch(`/api/recurring-expenses/${template.id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ isActive: !template.isActive })
      });
      if (!res.ok) {
        const errorData = await res.json().catch(() => ({}));
        throw new Error(errorData.message || "Failed to update template");
      }
      toast.success(
        template.isActive ? "Template paused" : "Template activated"
      );
      await queryClient.invalidateQueries({ queryKey: ["recurring-expenses"] });
    } catch (err) {
      toast.error(getErrorMessage(err, "Error updating template"));
    }
  };

  const deleteTemplate = async (template: RecurringTemplate) => {
    if (
      !confirm(
        `Delete the "${template.category}" recurring template? This cannot be undone.`
      )
    ) {
      return;
    }
    try {
      const res = await fetch(`/api/recurring-expenses/${template.id}`, {
        method: "DELETE"
      });
      if (!res.ok) {
        const errorData = await res.json().catch(() => ({}));
        throw new Error(errorData.message || "Failed to delete template");
      }
      toast.success("Recurring template deleted");
      await queryClient.invalidateQueries({ queryKey: ["recurring-expenses"] });
    } catch (err) {
      toast.error(getErrorMessage(err, "Error deleting template"));
    }
  };

  const runGeneration = async () => {
    setIsGenerating(true);
    try {
      const res = await fetch("/api/recurring-expenses/run", {
        method: "POST"
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        throw new Error(data.message || "Failed to generate expenses");
      }
      const generated = Number(data.generated) || 0;
      let message = "No recurring expenses were due";
      if (generated > 0) {
        const suffix = generated === 1 ? "" : "s";
        message = `Generated ${generated} expense${suffix}`;
      }
      toast.success(message);
      await queryClient.invalidateQueries({ queryKey: ["expenses"] });
      await queryClient.invalidateQueries({ queryKey: ["recurring-expenses"] });
    } catch (err) {
      toast.error(getErrorMessage(err, "Error generating recurring expenses"));
    } finally {
      setIsGenerating(false);
    }
  };

  const columns: ColumnConfig<ExpenseRecord>[] = [
    {
      key: "date",
      header: "Date",
      width: "13%",
      sortable: true,
      accessor: (e) => (e.date ? new Date(e.date) : null),
      render: (e) => (
        <span className="text-foreground text-xs font-semibold whitespace-nowrap">
          {formatDate(e.date)}
        </span>
      )
    },
    {
      key: "type",
      header: "Type",
      width: "10%",
      sortable: true,
      accessor: (e) => e.type,
      render: (e) =>
        e.type === "FIXED" ? (
          <Badge variant="navy">Fixed</Badge>
        ) : (
          <Badge variant="outline">Manual</Badge>
        )
    },
    {
      key: "category",
      header: "Category",
      width: "15%",
      sortable: true,
      accessor: (e) => e.category,
      render: (e) => (
        <span className="text-foreground text-xs font-bold">{e.category}</span>
      )
    },
    {
      key: "description",
      header: "Description",
      width: "20%",
      render: (e) => (
        <span
          className="text-muted-foreground block max-w-56 truncate text-xs"
          title={e.description}
        >
          {e.description}
        </span>
      )
    },
    {
      key: "amount",
      header: "Amount",
      width: "14%",
      align: "right",
      sortable: true,
      accessor: (e) => e.amount,
      render: (e) => (
        <span className="text-foreground font-mono text-xs font-bold whitespace-nowrap">
          {formatPKR(Number(e.amount) || 0)}
        </span>
      )
    },
    {
      key: "paymentMethod",
      header: "Payment",
      width: "12%",
      accessor: (e) => e.paymentMethod ?? "",
      render: (e) => (
        <span className="text-muted-foreground text-xs">
          {e.paymentMethod || "-"}
        </span>
      )
    },
    {
      key: "source",
      header: "Source",
      width: "9%",
      sortable: true,
      accessor: (e) => (e.isAutoGenerated ? "Auto" : "Manual"),
      render: (e) =>
        e.isAutoGenerated ? (
          <span className="text-violet bg-violet/10 border-violet/20 inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[11px] font-bold">
            <Repeat className="h-3 w-3" />
            Auto
          </span>
        ) : (
          <span className="text-muted-foreground text-[11px] font-semibold">
            Manual
          </span>
        )
    },
    {
      key: "actions",
      header: "Actions",
      width: "7%",
      align: "right",
      render: (e) => (
        <div className="flex items-center justify-end gap-1.5">
          <button
            type="button"
            onClick={() => deleteExpense(e)}
            className="border-border bg-card hover:bg-destructive/10 hover:text-destructive text-muted-foreground cursor-pointer rounded-lg border p-1.5 transition-colors"
            title="Delete expense"
            aria-label={`Delete ${e.category} expense`}
          >
            <Trash2 className="h-3.5 w-3.5" />
          </button>
        </div>
      )
    }
  ];

  return (
    <div className="space-y-6">
      {/* 1. KPI Summary */}
      <SummaryStrip
        metrics={[
          {
            label: "This Month",
            value: formatPKR(stats.thisMonth)
          },
          {
            label: "Fixed Total",
            value: formatPKR(stats.fixed),
            accentColor: "var(--success)"
          },
          {
            label: "Manual Total",
            value: formatPKR(stats.manual),
            accentColor: "var(--warning)"
          },
          ...(isOwner
            ? [
                {
                  label: "Active Templates",
                  value: String(stats.activeTemplates),
                  accentColor: "var(--destructive)"
                }
              ]
            : [])
        ]}
      />

      {/* 2. Action Bar */}
      <section className="flex flex-col justify-between gap-4 md:flex-row md:items-center">
        <p className="text-muted-foreground text-sm font-semibold">
          Recording & tracking firm spending. Fixed items pair with recurring
          templates for automation.
        </p>
        <div className="flex items-center gap-2">
          {isOwner && (
            <Button
              variant="outline"
              onClick={() => runGeneration()}
              disabled={isGenerating}
              className="border-border h-10 rounded-md text-sm font-semibold dark:border-white/40"
            >
              <RefreshCcw className="size-4" />
              Run Recurring
            </Button>
          )}
          <Button
            onClick={() => setIsCreateOpen(true)}
            className="h-10 rounded-md text-sm font-bold"
          >
            <Plus className="size-5" />
            Record Expense
          </Button>
        </div>
      </section>

      {/* 3. Expenses Ledger */}
      <Card className="border-border bg-card overflow-hidden rounded-2xl shadow-xs">
        <CardHeader className="border-border flex flex-row items-center justify-between border-b px-6 py-4">
          <CardTitle className="flex items-center gap-2 text-sm font-extrabold tracking-tight">
            <Receipt className="text-primary h-4 w-4" />
            Expenses Ledger
          </CardTitle>
          <div className="text-muted-foreground text-xs font-semibold">
            {expenses.length} total records
          </div>
        </CardHeader>
        <CardContent className="p-0">
          <CustomTable
            columns={columns}
            data={expenses}
            rowKey={(e) => e.id}
            isLoading={expensesQuery.isLoading}
            loadingLabel="Loading expenses ledger..."
            emptyIcon={
              <Receipt className="text-muted-foreground/60 mx-auto h-12 w-12" />
            }
            emptyTitle="No expenses recorded"
            emptyDescription="Record a fixed or manual expense to begin building the ledger."
            caption="Expenses ledger"
            pageSize={8}
          />
        </CardContent>
      </Card>

      {/* 4. Recurring Templates */}
      {isOwner && (
        <RecurringTemplatesSection
          templates={templates}
          isLoading={templatesQuery.isLoading}
          isGenerating={isGenerating}
          onGenerate={runGeneration}
          onCreate={() => setIsTemplateOpen(true)}
          onToggleActive={toggleTemplate}
          onDelete={deleteTemplate}
        />
      )}

      {/* Dialogs */}
      <CreateExpenseDialog open={isCreateOpen} onOpenChange={setIsCreateOpen} />
      <RecurringTemplatesDialog
        open={isTemplateOpen}
        onOpenChange={setIsTemplateOpen}
      />
    </div>
  );
}
