graph LR
  AiModule --> AppModule
  AssociatesModule --> AppModule
  AttendanceModule --> AppModule
  AuthModule --> AppModule
  CaseDocumentsModule --> AppModule
  ClientsModule --> AppModule
  CloudinaryModule --> AuthModule
  CloudinaryModule --> TasksModule
  ExpensesModule --> AppModule
  ExpensesModule --> FixedExpensesModule
  ExpensesModule --> ManualExpensesModule
  ExpensesModule --> RecurringExpensesModule
  FirmsModule --> AppModule
  FixedExpensesModule --> AppModule
  HearingsModule --> AppModule
  LeaveModule --> AppModule
  MailModule --> AuthModule
  ManualExpensesModule --> AppModule
  MattersModule --> AppModule
  MattersModule --> CaseDocumentsModule
  MattersModule --> HearingsModule
  PrismaModule --> AiModule
  PrismaModule --> AppModule
  PrismaModule --> AssociatesModule
  PrismaModule --> AttendanceModule
  PrismaModule --> AuthModule
  PrismaModule --> CaseDocumentsModule
  PrismaModule --> ClientsModule
  PrismaModule --> CloudinaryModule
  PrismaModule --> ExpensesModule
  PrismaModule --> FirmsModule
  PrismaModule --> FixedExpensesModule
  PrismaModule --> HearingsModule
  PrismaModule --> LeaveModule
  PrismaModule --> MailModule
  PrismaModule --> ManualExpensesModule
  PrismaModule --> MattersModule
  PrismaModule --> RecurringExpensesModule
  PrismaModule --> TasksModule
  PrismaModule --> UsersModule
  RecurringExpensesModule --> AppModule
  TasksModule --> AppModule
  UsersModule --> AppModule
  UsersModule --> AssociatesModule
  UsersModule --> AttendanceModule
  UsersModule --> CaseDocumentsModule
  UsersModule --> ClientsModule
  UsersModule --> FirmsModule
  UsersModule --> HearingsModule
  UsersModule --> LeaveModule
  UsersModule --> MattersModule
  UsersModule --> TasksModule
